name: Upload release assets

permissions:
  contents: write

on:
  release:
    types:
      - created

jobs:
  build-deb:
    name: Build and upload deb package
    runs-on: ubuntu-24.04
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc libglib2.0-dev libgtk-4-dev libadwaita-1-dev libddcutil-dev

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Initialize ddcbc-api git submodule
        run: git submodule update --init ddcbc-api

      - name: Build package
        run: ./build-deb.sh

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/luminance.deb
          asset_name: luminance-${{ github.event.release.tag_name }}.deb
          tag: ${{ github.ref }}

  build-rpm:
    name: Build and upload rpm package
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
      - name: Install dependencies
        run: |
          sudo dnf -y upgrade
          sudo dnf install -y git-all gcc glib2-devel gtk4-devel libadwaita-devel libddcutil-devel fedora-packager rpmdevtools

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Initialize ddcbc-api git submodule
        run: |
          git config --global --add safe.directory /__w/Luminance/Luminance
          git submodule update --init ddcbc-api

      - name: Build package
        run: ./build-rpm.sh

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./build/luminance.rpm
          asset_name: luminance-${{ github.event.release.tag_name }}.rpm
          tag: ${{ github.ref }}
